### ISSUE TITLE
Question regarding outbound traffic

### ISSUE THREAD

**Issue by postmart** [erjosito/azure-networking-lab#6]
Great documentation and lab exercises! Thanks a lot for sharing this material.

I have a question regarding inspecting outbound internet connection with an NVA device. It is mentioned in your documentation that we `need to make sure that Internet traffic to/from all VMs flows through the NVAs via User-Defined Routes, that NVAs source-NAT the outgoing traffic with their public IP address, and that NVAs have Internet connectivity`.
Could you explain in more details the necessity of SNAT? Sorry, I am still trying to wrap my head around azure networking. 
Let's assume there is a single NVA instance, and it is `not` behind an ILB. In this case, NVA has outbound connection and there must be some kind of NAT Gateway available for each VNET. 
Since NVA has an outbound connection, could it just use it for the outbound traffic from protected instances? I assume that the answer is "No". Could you let me know why? Will NAT GW drop these packets? Or traffic will still go through the NAT, but response won't be handled properly? 

Thanks a lot!

**Comment by ernani** [comment]
I guess you need the SNAT to ensure that the outbound IP address is the same as the inbound IP address to avoid asymmetrical issues when routing traffic, but I will let the author comment more.
